---
   - name: "Ansible sample testing"
     hosts: localhost
     become: true
     tasks:

        - name: "host reachability"
          ping:

        - name: "Removes hello.txt file if it exists"
          ansible.builtin.shell:
            cmd: rm -f hello.txt

        - name: "Creating file and inserting text into it"
          ansible.builtin.shell:
            cmd: echo "Hello there! this is the file created again" >> hello.txt

        - name: "Output the text inside file"
          ansible.builtin.shell:
            cmd: cat hello.txt
 
